from ROOT import *

def stackHist(hist, title, xtitle, outname):
	f_ttbb_1 = TFile('/home/juhee5819/cheer/HiggsAnalysis/combineTool/fit/afterFit/ttbb_Gen_1.root')
	f_ttbb_2 = TFile('/home/juhee5819/cheer/HiggsAnalysis/combineTool/fit/afterFit/ttbb_Gen_2.root')
	f_ttbb_3 = TFile('/home/juhee5819/cheer/HiggsAnalysis/combineTool/fit/afterFit/ttbb_Gen_3.root')
	f_ttbb_4 = TFile('/home/juhee5819/cheer/HiggsAnalysis/combineTool/fit/afterFit/ttbb_Gen_4.root')
	f_ttbj = TFile('/home/juhee5819/cheer/HiggsAnalysis/combineTool/fit/afterFit/multiplied_ttbj.root')
	f_ttcc = TFile('/home/juhee5819/cheer/HiggsAnalysis/combineTool/fit/afterFit/multiplied_ttcc.root')
	f_Bkg = TFile('/home/juhee5819/cheer/HiggsAnalysis/combineTool/fit/afterFit/multiplied_Bkg.root')
	f_data = TFile('/home/juhee5819/cheer/HiggsAnalysis/combineTool/scale/scaled/merge_ran.root')

	
	h_ttbb_1 = f_ttbb_1.Get(hist)
	h_ttbb_1.SetFillColor(42)
	#h_ttbb_1.SetFillColor(205)
	#h_ttbb_1.SetFillColor(kViolet-1)
	h_ttbb_1.SetLineColor(kBlack)
	h_ttbb_2 = f_ttbb_2.Get(hist)
	h_ttbb_2.SetFillColor(45)
	#h_ttbb_2.SetFillColor(206)
	#h_ttbb_2.SetFillColor(kViolet-2)
	h_ttbb_2.SetLineColor(kBlack)
	h_ttbb_3 = f_ttbb_3.Get(hist)
	h_ttbb_3.SetFillColor(46)
	#h_ttbb_3.SetFillColor(207)
	#h_ttbb_3.SetFillColor(kViolet-3)
	h_ttbb_3.SetLineColor(kBlack)
	h_ttbb_4 = f_ttbb_4.Get(hist)
	h_ttbb_4.SetFillColor(47)
	#h_ttbb_4.SetFillColor(208)
	#h_ttbb_4.SetFillColor(kViolet-4)
	h_ttbb_4.SetLineColor(kBlack)
	
	h_ttbj = f_ttbj.Get(hist)
	h_ttbj.SetFillColor(30)
	#h_ttbj.SetFillColor(186)
	#h_ttbj.SetFillColor(kMagenta-5)
	h_ttbj.SetLineColor(kBlack)
	h_ttcc = f_ttcc.Get(hist)
	h_ttcc.SetFillColor(40)
	#h_ttcc.SetFillColor(180)
	#h_ttcc.SetFillColor(kMagenta-8)
	h_ttcc.SetLineColor(kBlack)
	h_Bkg = f_Bkg.Get(hist)
	h_Bkg.SetFillColor(20)
	#h_Bkg.SetFillColor(175)
	#h_Bkg.SetFillColor(kMagenta-10)
	h_Bkg.SetLineColor(kBlack)
	
	h_data = f_data.Get(hist)
	h_data.SetLineColor(kBlack)
	h_data.SetMarkerSize(1)
	h_data.SetMarkerStyle(20)

	c = TCanvas('c', 'c', 3)
	c.SetLeftMargin(0.15)
	gStyle.SetOptStat(0)
	st = THStack(title, title)
	st.Add(h_ttbb_1)
	st.Add(h_ttbb_2)
	st.Add(h_ttbb_3)
	st.Add(h_ttbb_4)
	st.Add(h_ttbj)
	st.Add(h_ttcc)
	st.Add(h_Bkg)
	
	maxi = st.GetMaximum() * 1.3
	st.SetMaximum(maxi)
	
	st.Draw('hist')
	h_data.Draw('same p')

	st.GetXaxis().SetTitle(xtitle)
	st.GetYaxis().SetTitle('Entries')
	gPad.Modified()
	gPad.Update()
	
	leg = TLegend(.2, .75, .85, .88)
	leg.SetTextSize(0.03)
	leg.SetNColumns(4)
	leg.SetBorderSize(0)
	leg.AddEntry(h_ttbb_1, 'ttbb Gen1')
	leg.AddEntry(h_ttbb_2, 'ttbb Gen2')
	leg.AddEntry(h_ttbb_3, 'ttbb Gen3')
	leg.AddEntry(h_ttbb_4, 'ttbb Gen4')
	leg.AddEntry(h_ttbj, 'ttbj')
	leg.AddEntry(h_ttcc, 'ttcc')
	leg.AddEntry(h_Bkg, 'ttLF+ttother')
	leg.AddEntry(h_data, 'Pseudo data')
	leg.Draw('same')
	
	c.Print(outname)

stackHist('h_1stProb', '1st prob.', 'The highest probability', 'h_1stProb_doubleFit_stack2.pdf')
#stackHist('h_Pttbb', 'ttbb prob.', 'Probability to be ttbb', 'h_Pttbb_stack.pdf')

